// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_J6SPzzu1jVfiPieiHntOMV1EDn6XrQ',
    appId: '1:586582771592:web:e1cb47a761ccc4693c1c3d',
    messagingSenderId: '586582771592',
    projectId: 'todo-app-60751',
    authDomain: 'todo-app-60751.firebaseapp.com',
    storageBucket: 'todo-app-60751.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeZnWBRPpyyA7zygypVN3Ci8zNZRyy-2w',
    appId: '1:586582771592:android:5095b5eed615e8323c1c3d',
    messagingSenderId: '586582771592',
    projectId: 'todo-app-60751',
    storageBucket: 'todo-app-60751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bCCZQo_MjZfyHL-23y5f5WJAPt0ocp4',
    appId: '1:586582771592:ios:326859407ef03a8f3c1c3d',
    messagingSenderId: '586582771592',
    projectId: 'todo-app-60751',
    storageBucket: 'todo-app-60751.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8bCCZQo_MjZfyHL-23y5f5WJAPt0ocp4',
    appId: '1:586582771592:ios:326859407ef03a8f3c1c3d',
    messagingSenderId: '586582771592',
    projectId: 'todo-app-60751',
    storageBucket: 'todo-app-60751.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf_J6SPzzu1jVfiPieiHntOMV1EDn6XrQ',
    appId: '1:586582771592:web:01e67a18e40b5bb83c1c3d',
    messagingSenderId: '586582771592',
    projectId: 'todo-app-60751',
    authDomain: 'todo-app-60751.firebaseapp.com',
    storageBucket: 'todo-app-60751.firebasestorage.app',
  );
}
